### ISSUE TITLE
Documentation: Clicking a link that leads to another documentation page creates an infinite loop, creates an infinte loop, creates an infinite loop, crea..

### ISSUE THREAD

**Issue by BartuCulha** [PrimeDAO/prime-deals-dapp#1088]
Steps to reproduce:
1. Navigate here: https://prime-deals-dapp-git-refac-deals-au2-curvelabs.vercel.app/documentation
2. Click the link that says "here" under "Why should I use Prime Deals?"

Console log throws:
Uncaught (in promise) Error: 1 remaining instructions after 100 iterations; there is likely an infinite loop.
    at entry.8e09c9544862f83b3642.bundle.js:2:3489364
    at Hn.unresolvedInstructionsError (entry.8e09c9544862f83b3642.bundle.js:2:3489542)
    at Dn.processInstructions (entry.8e09c9544862f83b3642.bundle.js:2:3460014)
    at async Hn.processNavigation (entry.8e09c9544862f83b3642.bundle.js:2:3484356)

**Comment by BartuCulha** [comment]
Additional update: 
After you follow the steps to reproduce this bug, when you refresh the page, dapp will not load and console will display:

Uncaught (in promise) Error: 'home' did not match any configured route or registered component name - did you forget to add the component 'home' to the dependencies or to register it as a global dependency?
    at An.createComponent (entry.8e09c9544862f83b3642.bundle.js:2:3418874)
    at pn.<anonymous> (entry.8e09c9544862f83b3642.bundle.js:2:3433389)
    at fn.process (entry.8e09c9544862f83b3642.bundle.js:2:3404413)
    at fn.run (entry.8e09c9544862f83b3642.bundle.js:2:3403252)
    at Tn.transition (entry.8e09c9544862f83b3642.bundle.js:2:3432627)
    at Bn.run (entry.8e09c9544862f83b3642.bundle.js:2:3476182)
    at Dn.processInstructions (entry.8e09c9544862f83b3642.bundle.js:2:3461335)
    at async Hn.pro

**Comment by testing-life** [comment]
that's related to general router problems and other reported issues
#1087

**Comment by hiaux0** [comment]
Latest testing on https://prime-deals-au2-staging.vercel.app/documentation seemed okay again

**Comment by BartuCulha** [comment]
Still getting the same bug.

Console log:

Uncaught (in promise) Error: 'home' did not match any configured route or registered component name - did you forget to add the component 'home' to the dependencies or to register it as a global dependency?
    at _n.createComponent (entry.fe359000edc26d3abcca.bundle.js:2:4379209)
    at gn.<anonymous> (entry.fe359000edc26d3abcca.bundle.js:2:4393225)
    at mn.process (entry.fe359000edc26d3abcca.bundle.js:2:4364151)
    at mn.process (entry.fe359000edc26d3abcca.bundle.js:2:4364015)
    at mn.run (entry.fe359000edc26d3abcca.bundle.js:2:4362990)
    at Cn.transition (entry.fe359000edc26d3abcca.bundle.js:2:4392463)
    at Yn.run (entry.fe359000edc26d3abcca.bundle.js:2:4436257)
    at On.processInstructions (entry.fe359000edc26d3abcca.bundle.js:2:4421410)
    at async Vn.processNavigation (entry.fe359000edc26d3abcca.bundle.js:2:4444431)
entry.fe359000edc26d3abcca.bundle.js:2 Error: 1 remaining instructions after 100 iterations; there is likely an infinite loop.
    at entry.fe359000edc26d3abcca.bundle.js:2:4449439
    at Vn.unresolvedInstructionsError (entry.fe359000edc26d3abcca.bundle.js:2:4449617)
    at On.processInstructions (entry.fe359000edc26d3abcca.bundle.js:2:4420089)
    at async Promise.all (index 0)
    at async On.processInstructions (entry.fe359000edc26d3abcca.bundle.js:2:4422132)
    at async Vn.processNavigation (entry.fe359000edc26d3abcca.bundle.js:2:4444431) Array(1)
entry.fe359000edc26d3abcca.bundle.js:2 Uncaught (in promise) Error: 1 remaining instructions after 100 iterations; there is likely an infinite loop.
    at entry.fe359000edc26d3abcca.bundle.js:2:4449439
    at Vn.unresolvedInstructionsError (entry.fe359000edc26d3abcca.bundle.js:2:4449617)
    at On.processInstructions (entry.fe359000edc26d3abcca.bundle.js:2:4420089)
    at async Promise.all (index 0)
    at async On.processInstructions (entry.fe359000edc26d3abcca.bundle.js:2:4422132)
    at async Vn.processNavigation (entry.fe359000edc26d3abcca.bundle.js:2:4444431)
