### ISSUE TITLE
Cannot create a discussion for the 2nd clause

### ISSUE THREAD

**Issue by BartuCulha** [PrimeDAO/prime-deals-dapp#1155]
1. Navigate here:https://prime-deals-dapp-jhff2ozmg-curvelabs.vercel.app/deal/5fVjBaQc36MxuMGqSzizTG
2. Connect wallet: 0xE834627cDE2dC8F55Fe4a26741D3e91527A8a498
3. Try to create a discussion for the 2nd cluase

Result:
Nothing will happen and console log will throw:

entry.223ea0a2b3cab3a3bf42.bundle.js:2 Uncaught (in promise) Error: FirebaseError: [code=invalid-argument]: Function setDoc() called with invalid data. Document fields must not be empty (found in field clauseDiscussions.`` in document deals-token-swap/5fVjBaQc36MxuMGqSzizTG)
    at U.addClauseDiscussion (entry.223ea0a2b3cab3a3bf42.bundle.js:2:3178561)
    at Tc.addClauseDiscussion (entry.223ea0a2b3cab3a3bf42.bundle.js:2:4606204)
    at Ps.addClauseDiscussion (entry.223ea0a2b3cab3a3bf42.bundle.js:2:4545336)
    at gu.createDiscussion (entry.223ea0a2b3cab3a3bf42.bundle.js:2:4696411)
    at async jh.addOrReadDiscussion (entry.223ea0a2b3cab3a3bf42.bundle.js:2:4761614)

**Comment by hiaux0** [comment]
@BartuCulha
 FYI, a fix was introduced, but may still happen for already created clauses.
For

When the console says sth about 
```
Document fields must not be empty (found in field clauseDiscussions.`` in document deals-token-swap/5fVjBaQc36MxuMGqSzizTG)
```
Would be nice if you can share the dealId (eg. `5fVjBaQc36MxuMGqSzizTG`), because the deal clause is corrupted in the database.

![image.png](https://images.zenhubusercontent.com/61d459cd2e1f45dd77990d23/64858129-3ff8-4e39-ae0d-1e8792ea80ee)
