### ISSUE TITLE
Discussions: when a comment is deleted, it should indicate that immediately in replies to that comment. 

### ISSUE THREAD

**Issue by giladt** [PrimeDAO/prime-deals-dapp#444]
## Current
If a comment has been replied to and afterward has been deleted, then the preview in the reply should be changed into "This message has been removed" immediately and not only after a page refresh:

![delete-reply.gif](https://images.zenhubusercontent.com/60c89178ac3fd01fa6c9ba4a/ac17f499-547e-4dd4-8fd6-71e7a0964c04)

## Expected
![image.png](https://images.zenhubusercontent.com/60c89178ac3fd01fa6c9ba4a/97bc5e2d-f49a-4e96-a7fe-ac5bc7d15337)

**Comment by BartuCulha** [comment]
Found a bug:
1. Navigate here https://prime-deals-staging.vercel.app/deal/hW6r5BHVKLBYSiLWitoF4E
2. connect wallet
3. Write a comment
4. Delete it


When you click delete, comment will be gone for few seconds and reappear again. 
clicking delete second time will delete the comment

**Comment by giladt** [comment]
Fixed in PR#573

**Comment by BartuCulha** [comment]
Able to reproduce: 
![DEAL-Dashboard-Prime-Deals (12)](https://user-images.githubusercontent.com/24368665/162022383-7baaf0fd-2a42-4f4d-b893-beff1dc78a8a.png)

**Comment by curvelabs-dev** [comment]
According to @giladt 👍 

The original fix to this ticket is somehow removed. It should be something like: 

On discussionThread`->`deleteComment, right after deleting the item from threadDictionary (line 391), we need to filter out all comments which indicates a reply to this message:

```
Object.values(this.threadDictionary).forEach((comment: IComment) => {
  if (comment.replyTo === _id) {
    comment.replyTo = "--deleted--";
  }
});
```

**Comment by BartuCulha** [comment]
An update: I received this error message when I made a new comment.

DEAL-Dashboard-Prime-Deals (5)

Console log:
Uncaught TypeError: Cannot read properties of undefined (reading 'firstChild')
at e.move (vendors-46804203.1d07dd8d57965b338a32.bundle.js:1:30346)
at e.moveView (vendors-3ce50090.04a2b4d6b86af11f3ae3.bundle.js:1:37992)
at v (vendors-3ce50090.04a2b4d6b86af11f3ae3.bundle.js:1:26201)

**Comment by BartuCulha** [comment]
This issue I have mentioned in the comment above occured again.

an unexpected error occurred
e.error @ vendors-319a6989.aebebf5e99f9a872fb4e.bundle.js:2
vendors-3ce50090.04a2b4d6b86af11f3ae3.bundle.js:1 Uncaught TypeError: Cannot read properties of undefined (reading 'firstChild')
    at e.move (vendors-46804203.1d07dd8d57965b338a32.bundle.js:1:30346)
    at e.moveView (vendors-3ce50090.04a2b4d6b86af11f3ae3.bundle.js:1:37992)
    at v (vendors-3ce50090.04a2b4d6b86af11f3ae3.bundle.js:1:26201)
    at t.instanceChanged (vendors-3ce50090.04a2b4d6b86af11f3ae3.bundle.js:1:26450)
    at e.itemsChanged (vendors-3ce50090.04a2b4d6b86af11f3ae3.bundle.js:1:35683)
    at e.n [as selfSubscriber] (vendors-cfc888f5.3888f45589f2d3162b0b.bundle.js:1:1303)
    at e.call (vendors-46804203.1d07dd8d57965b338a32.bundle.js:1:54385)
    at e.i.Vh.setValue (vendors-cfc888f5.3888f45589f2d3162b0b.bundle.js:1:999)
    at e.set [as items] (vendors-46804203.1d07dd8d57965b338a32.bundle.js:1:55747)
    at Object.setValue (vendors-90a7811f.c3fd5338d3093435d3b4.bundle.js:1:54633)
