### ISSUE TITLE
Discussion: 

### ISSUE THREAD

**Issue by BartuCulha** [PrimeDAO/prime-deals-dapp#599]
Navigate here:
https://prime-deals-staging.vercel.app/deal/3z9cNENzFJ8NFLtekde7cg
Click Discuss Button next to the clauses 

Currenlty: 
App gets stuck at loading comments 
![DEAL-Dashboard-Prime-Deals (9).png](https://images.zenhubusercontent.com/609a9f5f0a40bdfde66fe338/c37cb681-b940-4910-8fd1-2114cb282112)

And throws this error:
app-9a8b795a.b9ec9e5c21a5a89c05d6.bundle.js:1 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'length')
    at y.ensureDealDiscussion (app-9a8b795a.b9ec9e5c21a5a89c05d6.bundle.js:1:56065)
    at async y.initialize (app-9a8b795a.b9ec9e5c21a5a89c05d6.bundle.js:1:54537)

**Comment by giladt** [comment]
Since the error originates `theconvo.space` / `textile.io` - how should the application handle this?
1. popup?
2. try to reload after a few seconds, until success?
Ideas? @dkent600 @BartuCulha @blink-km

**Comment by BartuCulha** [comment]
an error message, that says users to refresh and try again? Doug was not happy about refreshing right?

**Comment by hiaux0** [comment]
Suggestion:
- retry counter (no reloading needed)

![image.png](https://images.zenhubusercontent.com/61d459cd2e1f45dd77990d23/a3ac66b2-a05f-488a-85f8-ee16ee43d17e)
