### ISSUE TITLE
Discussion: remove all instances of a comment, if it gets deleted

### ISSUE THREAD

**Issue by BartuCulha** [PrimeDAO/prime-deals-dapp#634]
Steps to reproduce:
1.Go to an open proposal
2.Connect your wallet and begin a discussion
3. Write a new  comment and then reply to your own comment
4. Delete your original comment

Currently:
Original comment gets deleted but its still visible as a quote in the last comment
![DEAL-Dashboard-Prime-Deals (4).png](https://images.zenhubusercontent.com/609a9f5f0a40bdfde66fe338/8dec3d1d-7d36-450f-90ee-655f431bee9e)

Expected: Remove the quote but keep the reply.

**Comment by BartuCulha** [comment]
An update: I received this error message when I made a new comment. Also first comment that says "try again" got removed. Which is weird because that was not the comment I have deleted.

![DEAL-Dashboard-Prime-Deals (5)](https://user-images.githubusercontent.com/24368665/162712603-a497f271-eeb2-46a0-b713-a8ddee6e129c.png)


Console log:
Uncaught TypeError: Cannot read properties of undefined (reading 'firstChild')
    at e.move (vendors-46804203.1d07dd8d57965b338a32.bundle.js:1:30346)
    at e.moveView (vendors-3ce50090.04a2b4d6b86af11f3ae3.bundle.js:1:37992)
    at v (vendors-3ce50090.04a2b4d6b86af11f3ae3.bundle.js:1:26201)
    at t.instanceChanged (vendors-3ce50090.04a2b4d6b86af11f3ae3.bundle.js:1:26450)
    at e.itemsChanged (vendors-3ce50090.04a2b4d6b86af11f3ae3.bundle.js:1:35683)
    at e.n [as selfSubscriber] (vendors-cfc888f5.3888f45589f2d3162b0b.bundle.js:1:1303)
    at e.call (vendors-46804203.1d07dd8d57965b338a32.bundle.js:1:54385)
    at e.i.Vh.setValue (vendors-cfc888f5.3888f45589f2d3162b0b.bundle.js:1:999)
    at e.set [as items] (vendors-46804203.1d07dd8d57965b338a32.bundle.js:1:55747)
    at Object.setValue (vendors-90a7811f.c3fd5338d3093435d3b4.bundle.js:1:54633)
