### ISSUE TITLE
Open Proposal Reg. Wiz: Stepper gets stuck 

### ISSUE THREAD

**Issue by BartuCulha** [PrimeDAO/prime-deals-dapp#923]
### Steps to reproduce:
1. Navigate here:
https://prime-deals-staging.vercel.app/initiate/token-swap/open-proposal/proposal
2. Go to other stages using the Stepper. 
3. Continue using the stepper to switch steps until it breaks

Result: You cannot use Stepper to navigate to other stages and console throws an error.
### Console log:
app-a1d170d4.a94101e6ed6291e1e8e7.bundle.js:1 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'name')
    at Object.condition (app-a1d170d4.a94101e6ed6291e1e8e7.bundle.js:1:73463)
    at c (vendors-cfc888f5.3888f45589f2d3162b0b.bundle.js:1:11904)
    at t.validateRuleSequence (vendors-cfc888f5.3888f45589f2d3162b0b.bundle.js:1:12103)
    at t.validate (vendors-cfc888f5.3888f45589f2d3162b0b.bundle.js:1:12293)
    at t.validateObject (vendors-cfc888f5.3888f45589f2d3162b0b.bundle.js:1:11134)
    at t (vendors-cfc888f5.3888f45589f2d3162b0b.bundle.js:1:17245)
    at async l.goToStage (app-a1d170d4.a94101e6ed6291e1e8e7.bundle.js:1:57267)

**Comment by hiaux0** [comment]
reported in #914

**Comment by dkent600** [comment]
Only took me two clicks to freeze, on step 3

**Comment by dkent600** [comment]
I also fixed so it does a case-insensitive dao name comparison
